#!/usr/bin/env bash
# This script prints information about domains and subdomains using DNS queries.

# Function to print information about a domain and subdomain
print_domain_subdomain () {
    # Use dig to retrieve DNS information for the given domain
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

# Check if the script is provided with exactly two command-line arguments
if [ "$#" -eq 2 ]
then
    # If two arguments are provided, call the function with the specified subdomain and domain
    print_domain_subdomain "$2.$1" "$2"
else
    # If not enough arguments are provided, print information for default subdomains
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1" "lb-01"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
fi
