#!/usr/bin/env bash
# Script that displays information about subdomains

domain=$1
subdomain=$2
result=

# Display the information about the result returned
display_domain_info() {
	record_type=$(echo "$result" | awk '{print $4}')
	ip_addr=$(echo "$result" | awk '{print $5}')
	echo -n "The subdomain $subdomain is a $record_type record and points "
	echo "to $ip_addr"
}

# Retrieve information about the subdomains
retrieve_domain_info () {
	if [[ $domain = "" ]]; then
		echo "Domain name missing."
		exit 1
	fi

	if [[ $subdomain = "" ]]; then
		known_sub_domains=("www" "lb-01" "web-01" "web-02")
		for subdomain in "${known_sub_domains[@]}"; do
			result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION'\
				| tail -1)
			display_domain_info
		done
		exit
	fi

	result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION' | tail -1)
	display_domain_info
}

retrieve_domain_info
