#!/usr/bin/env bash
# script that installs the Nginx web server and configures the initial "Hello
# world" page.

if [[ $EUID -ne 0 ]]; then
	echo "ERROR: You need to be root" 1>&2
	exit 1
fi

# Update the package list and install Nginx if not present
apt-get update
apt-get install -y nginx

# Create the default "Hello world" page
echo "Hello World!" > /var/www/html/index.html

echo -e "\tserver_name _;
\tlocation /redirect_me {
	\t\treturn 301 https://drive.google.com/file/d/130vHZlceKje17SE9uPx8mAZWADVTs3XW/view?usp=sharing/;
	\t}" > /tmp/new_config

sed -i '/server_name _;/{
	r /tmp/new_config
	d
}' /etc/nginx/sites-available/default

# Start the Nginx service
service nginx restart

if [[ ! $? ]]; then
#if [[ $? -ne 0 ]]; then
	echo "ERROR: Failed to start Nginx" 1>&2
	exit 1
fi
