#!/usr/bin/env bash
# script that installs and configures the HAproxy load balancer. It configures
# the server to send traffic to two web servers. The load balanceing algorithm
# is round-robin.

# Define variables for web server IP addresses
WEB_SERVER_1_IP="34.224.62.190"
WEB_SERVER_2_IP="34.239.253.87"

# Add entries to /etc/hosts
echo "$WEB_SERVER_1_IP web-01.emyjakarta.tech" >> /etc/hosts
echo "$WEB_SERVER_2_IP web-02.emyjakarta.tech" >> /etc/hosts

# Function to resolve IP address from hostname
resolve_ip() {
	hostname=$1
	ip=$(dig +short $hostname)
	echo "$ip"
}

# Configuration for HAProxy
config="
frontend emyjakarta_frontend
	bind *:80
	mode http
	default_backend emyjakarta_backend

backend emyjakarta_backend
	balance roundrobin
	server 527465-web-01 $(resolve_ip web-01.emyjakarta.tech):80 check
	server 527465-web-02 $(resolve_ip web-02.emyjakarta.tech):80 check
"
# Check if the user is root
if [ $EUID -ne 0 ]; then
	echo "You must be root"
	exit 1
fi

function add_config() {
	# let's do some house checking first, ensure the configuration does not 
	# exist before we append to it
	grep -q -e "emyjakarta_frontend" -e "emyjakarta_backend" /etc/haproxy/haproxy.cfg

	status=$?
	if [[ $status -ne 0 ]]; then
		# configure HAproxy
		echo "$config" >> /etc/haproxy/haproxy.cfg
	else
		echo "Configuration already exists."
		exit
	fi

	grep -q "ENABLED" /etc/default/haproxy

	status=$?
	if [[ $status -ne 0 ]]; then
		echo "ENABLED=1" >> /etc/default/haproxy
	fi

	# restart HAproxy
	service haproxy restart
}

# let's save time and check if the HAproxy package is already installed
which haproxy > /dev/null

status=$?
if [[ $status -ne 0 ]]; then
	# update package list
	apt-get update -y

	# enable dedicated PPA for HAproxy 2.8
	apt-get install --no-install-recommends -y software-properties-common
	add-apt-repository -y ppa:vbernat/haproxy-2.8

	# install HAproxy
	apt-get install -y haproxy

	if [[ ! $? ]]; then
		echo "Failed to install HAproxy."
		exit 1
	fi

	add_config
else
	# HAproxy is already installed, just add the configuration
	add_config
fi
