#!/usr/bin/env bash
# install load balancer

echo -e "Updating and doing some minor checks...\n"

function install() {
    command -v "$1" &> /dev/null

    # shellcheck disable=SC2181
    if [ $? -ne 0 ]; then
        echo -e "    Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    ${1} is already installed.\n"
    fi
}

# Install haproxy
install haproxy

echo -e "\nSetting up some minor stuff.\n"

# Backup the default haproxy configuration file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Define haproxy server configuration
haproxy_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s
frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend
backend clickviral-tech-backend
    balance roundrobin
    server 436533-web-01 54.227.199.4:80 check
    server 436533-web-02 100.25.203.163:80 check
"

# shellcheck disable=SC2154
echo "$haproxy_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable haproxy to be started by the init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

# Check if haproxy is running and start/restart accordingly
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi
