#!/usr/bin/env bash
#Explains what OSI model
The OSI model is a conceptual model that characterizes the communication functions of a telecommunication system without regard to their underlying internal structure and technology2

#How is the OSI model organized?
From the lowest to the highest level
