#!/usr/bin/env bash
# This script will display numbers from 1 to 100 with FizzBuzz rules.

# Using a for loop to iterate from 1 to 100
for ((i=1; i<=100; i++)); do
	# Checking the conditions for Fizz, Buzz, and FizzBuzz
	if ((i % 3 == 0)) && ((i % 5 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
