#!/usr/bin/env bash
# This script will group visitors by IP and HTTP status code and displays the data.

# Using awk to extract, count occurrences, and sort data
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
