#!/usr/bin/env bash
# This script will display "Best School" 10 times

# Counter
count=0

# Using an until loop to display "Best School" 10 times
until [ $count -ge 10 ]; do
    echo "Best School"
        ((count++))
done
