#!/usr/bin/env bash
# This script will display "Best School" 10 times,
# but on the 9th iteration, it also says "Hi" on a new line.

# Counter
count=0

# Using a while loop to display "Best School" 10 times
while [ $count -lt 10 ]; do
	# Using an if statement to check if it's the 9th iteration
	if [ $count -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi

	((count++))
done
